# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               blog
tagline:             '@Sangyoung.me'
description:         '스스로 엔지니어라고 부르고 싶은 쪼렙 개발자(라고 쓰고 코더라고 읽는다) 의 본격 삽질 노트'
url:                 http://blog.sangyoung.me
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sangyoung Lee
  url:               https://twitter.com/Cluina
  email:             humanfly.fc@gmail.com

# Custom vars
version:             1.1.0
