# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               blog
tagline:             '@Sangyoung.me'
description:         '<img src="http://vincha.me/wp-content/uploads/2015/11/%EB%94%B0%EC%98%B4%ED%91%9C.png" style="width: 23px; margin-bottom: -35px;;"><h3 style="color: #fff;">Sangyoung.me</h3><span style="font-size:13px;">스스로 엔지니어라고 부르고 싶은<br>쪼렙 개발자<small>(라고 쓰고 코더라고 읽는다)</small> 의<br>본격 삽질 노트</span><br><br><span style="font-size: 20px; color: rgba(255,255,255,.6);"><a href="https://github.com/cluina" target="_blank" style="color: inherit;"><i class="fa fa-github" style="margin-right: 10px;"></i></a><a href="https://www.facebook.com/sangyoung.lee.391" target="_blank" style="color: inherit;"><i class="fa fa-facebook" style="margin-right: 10px;"></i></a><a href="mailto:lee@sangyoung.me" style="color: inherit;"><i class="fa fa-paper-plane"></i></a></span>'
url:                 https://cluina.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              SY LEE
  url:               https://twitter.com/Cluina
  email:             humanfly.fc@gmail.com

# Custom vars
version:             1.0.0
